### ISSUE TITLE
Issue with Atiro Codeforces Login

### ISSUE THREAD

**Issue by 2745518585** [Sukwants/Atiro#11] opened 2023-10-03 08:38 UTC
**Issue Description:**

**Operating System:** Windows 11 Home Chinese Insider Preview

**GCC Version:** g++.exe (x86_64-win32-seh-rev1, Built by MinGW-Builds project) 13.1.0

**Node.js Version:** 18.12.1

**Atiro Version:** 1.0.2

**Problem Description:**

When attempting to log in to Codeforces on Atiro, after entering password, the following page appears:
![image](https://github.com/Sukwants/Atiro/assets/96607031/07f3ea87-9460-4f7c-a9e3-f1fc32a7817d)

**Comment by Sukwants** [comment] 2023-10-03 09:13
That may be your own problem.

![image](https://github.com/Sukwants/Atiro/assets/95968907/a972a966-59e4-4c16-8846-de621c4d010a)

Please retry or try to login with the normal broswer.

**Comment by Sukwants** [comment] 2023-10-03 09:15
so retry, please

**Comment by 2745518585** [comment] 2023-10-03 09:16
retried

**Comment by Sukwants** [comment] 2023-10-03 09:18
how?

**Comment by 2745518585** [comment] 2023-10-03 09:19
run `atiro cf i` and login again, the result is same.

**Comment by Sukwants** [comment] 2023-10-03 09:21
I can't help more. Maybe you can ask Mike for help.

No one knows what rules Codeforces set to ban you, right?

Is it the problem of your network? Unset your proxy server and try again? It is possibly not the problem of Atiro.

**Comment by 2745518585** [comment] 2023-10-03 09:27
have tried unseting proxy server, that not work

**Comment by Sukwants** [comment] 2023-10-03 09:29
if you want to login, import the cookies deirectly

**Comment by Sukwants** [comment] 2023-10-03 09:31
@2745518585 set a new way to support importing cookies directly with atiro in the command line

**Comment by Sukwants** [comment] 2023-10-03 09:34
cookies are in `.json` type

remember to update the README, just Chinese README is okey

**Comment by Sukwants** [comment] 2023-10-06 09:09
The problem is caused by Codeforces's new rules of blocking headless browsers.

It is fixed in the version v1.0.4. Update your Atiro, please.

**Closed by Sukwants** 2023-10-06 09:09 UTC
Labels: bug
